name: Ruby CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.3', '3.4', '4.0']
        include:
          - os: ubuntu-latest
            ruby: '2.7'
            experimental: true
          - os: ubuntu-latest
            ruby: 'truffleruby'
            experimental: true
          - os: ubuntu-latest
            ruby: 'jruby'
            experimental: true
          - os: macos-latest
            ruby: '4.0'
            experimental: true
          - os: windows-latest
            ruby: '4.0'
            experimental: true

    runs-on: ${{ matrix.os }}

    # mark certain combos as optional so failures won't block merges:
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Java for JRuby
        if: ${{ matrix.ruby == 'jruby' }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Print versions
        run: |
          ruby -v
          gem -v
          bundle -v

      - name: Run linters and test suite
        run: bundle exec rake ci
